### ISSUE TITLE
Support non-app workspace root directory

### ISSUE THREAD

**Issue by barredterra** [ankush/frappe-test-runner#2]
With VSCode open on the bench level (working directory: /Users/raffael/Code/bench/develop), the dotted path is wrong: it starts with "apps.my-app.my-app" instead of "my-app".

```bash
> pwd
/Users/raffael/Code/bench/develop
> ls
Procfile    apps        archived    config      env         logs        patches.txt sites 
# Executing "Run Nearest Test" on "apps/frappe/frappe/contacts/doctype/contact/test_contact.py"
> bench --site erpnext run-tests --module apps.frappe.frappe.contacts.doctype.contact.test_contact  --test test_get_full_name
erpnext: SystemSettings.enable_scheduler is UNSET
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/raffael/Code/bench/develop/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/Users/raffael/Code/bench/develop/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/Users/raffael/Code/bench/develop/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/raffael/Code/bench/develop/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/raffael/Code/bench/develop/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/raffael/Code/bench/develop/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/raffael/Code/bench/develop/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/raffael/Code/bench/develop/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/raffael/Code/bench/develop/env/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/raffael/Code/bench/develop/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/raffael/Code/bench/develop/apps/frappe/frappe/commands/utils.py", line 793, in run_tests
    ret = frappe.test_runner.main(
  File "/Users/raffael/Code/bench/develop/apps/frappe/frappe/test_runner.py", line 109, in main
    ret = run_tests_for_module(
  File "/Users/raffael/Code/bench/develop/apps/frappe/frappe/test_runner.py", line 252, in run_tests_for_module
    module = importlib.import_module(module)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'apps'
```

**Comment by ankush** [comment]
This extension assumes that your root path is any one app and not bench or apps directory. :sweat_smile: 


https://github.com/ankush/frappe-test-runner/blob/6afa651f3732a303608e10feccb35fdbdc7e8838/src/extension.ts#L71-L77


Somewhat smarter approach would be to check if the path is actually an app or not.

**Comment by ankush** [comment]
VS Code doesn't give simple FS access api as far as I can tell. I was thinking of...

1. Get the parent bench path using same method as bench. 
2. Strip off `bench/app` path
3. Now the directory will be `app/app/...` we can pop first directory and get exact path.

**Comment by ankush** [comment]
I think better option would be just implement `--file` in Frappe's test runner instead of writing hacks in this extension :laughing:

**Comment by Abadulrehman** [comment]
@ankush How about having a config that allows users to set common workspace roots (i.e `bench`, `apps`, `single_app`). With this, we can just look at the config and have static steps to form the correct test dir. 

I think this will very useful, as a common dev pattern is to work from the bench directory (not sure about the apps dir).

I can open a PR if you'd like?

**Comment by ankush** [comment]
@Abadulrehman I think VS code lets you configure settings from project specific JSON file? If that's the case then people can configure site and path from local setting and use multiple benches without having to set it everytime.

If that's what you're proposing then go ahead.
